import j1 from "../assets/products/streetwear/j1.jpg";
import j2 from "../assets/products/streetwear/j2.jpg";
import j3 from "../assets/products/streetwear/j3.jpg";
import j4 from "../assets/products/streetwear/j4.jpg";
import p1 from "../assets/products/streetwear/p1.jpg";
import p2 from "../assets/products/streetwear/p2.jpg";
import p3 from "../assets/products/streetwear/p3.jpg";
import t1 from "../assets/products/streetwear/t1.jpg";
import t2 from "../assets/products/streetwear/t2.jpg";
import t3 from "../assets/products/streetwear/t3.jpg";

import c1 from "../assets/products/outerwear/c1.jpg";
import c2 from "../assets/products/outerwear/c2.jpg";
import c3 from "../assets/products/outerwear/c3.jpg";
import c4 from "../assets/products/outerwear/c4.jpg";
import h1 from "../assets/products/outerwear/h1.jpg";
import h2 from "../assets/products/outerwear/h2.jpg";
import h3 from "../assets/products/outerwear/h3.png";

import b1 from "../assets/products/outerwear/b1.jpg";
import b2 from "../assets/products/outerwear/b2.jpg";
import b3 from "../assets/products/outerwear/b3.jpg";
import b4 from "../assets/products/outerwear/b4.jpg";
import b5 from "../assets/products/outerwear/b5.jpg";

import top1 from "../assets/products/streetwear/top1.jpg";
import top2 from "../assets/products/streetwear/top2.jpg";
import top3 from "../assets/products/streetwear/top3.jpg";
import top5 from "../assets/products/streetwear/top5.jpg";

export const Layerup = [
  { id: "sw-01", title: "D-Generation X Graphic Bomber Jacket", price: "245.00", tag: "LIMITED", sizes: ["M", "L", "XL"], image: j1, rating: 4.6, description: "A heavyweight bomber built for main-event energy. The bold graphic print is placed across a structured satin-touch shell, finished with ribbed cuffs and hem that lock in the classic bomber silhouette. Snap-button collar and dual side pockets add function without breaking the clean lines. Runs true to size — layer a hoodie underneath for the full oversized effect." },
  { id: "sw-02", title: "Olive Sherpa Fleece Half-Zip Hoodie", price: "165.00", tag: "NEW", sizes: ["S", "M", "L", "XL", "XXL"], image: j2, rating: 4.2, description: "Sherpa fleece through and through — thick, textured, and built to trap heat on cold mornings. The half-zip neckline sits high and the drop-shoulder cut gives it a relaxed, easy layer over tees or thermals. A single kangaroo pocket up front keeps hands warm on transit days. Olive tone pairs easily with denim, cargos, or joggers." },
  { id: "sw-03", title: "Quilted Leather Baroque Embroidered Jacket", price: "320.00", tag: "LIMITED", sizes: ["M", "L", "XL"], image: j3, rating: 4.8, description: "Quilted leather panels meet intricate baroque-style embroidery for a jacket that reads statement piece from across the room. The diamond-quilted body adds structure and warmth, while the gold-toned embroidery threading catches light on movement. Heavyweight construction holds a boxy, slightly cropped fit that's meant to be worn open over graphic tees. Limited run — sizing runs true." },
  { id: "sw-04", title: "Fleur-de-Lis Leather Bomber Jacket", price: "290.00", tag: null, sizes: ["S", "M", "L", "XL"], image: j4, rating: 3.9, description: "Premium faux leather bomber finished with repeating fleur-de-lis embossing across the chest and sleeves. The snap-down collar and ribbed knit trims give it a sharp, structured shape that holds up whether zipped or worn open. Interior is lightly lined for shoulder-season wear without adding bulk. A go-to layer for elevating a plain tee-and-jean fit." },
  { id: "sw-05", title: "Sauron Graphic Oversized Tee — LOTR Collab", price: "85.00", tag: "NEW", sizes: ["S", "M", "L", "XL"], image: t1, rating: 4.7, description: "Officially licensed Lord of the Rings graphic tee featuring Sauron artwork printed across a heavyweight 240gsm cotton base. The oversized drop-shoulder fit and boxy body are built for the stacked streetwear look, and the pre-washed finish gives it that lived-in feel straight out of the bag. Double-stitched hems hold up through repeated washing without the print cracking." },
  { id: "sw-06", title: "Prince Daemon Acid-Wash Oversized Tee", price: "80.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: t2, rating: 4.1, description: "Acid-wash treatment means every single tee comes out with its own one-of-a-kind marbled pattern — no two are identical. Built on an oversized, boxy cut with dropped shoulders and a slightly longer hem for layering under jackets. The heavyweight cotton base holds its shape wash after wash instead of stretching out. Named for the Daemon Targaryen aesthetic — moody, weathered, and built to last." },
  { id: "sw-07", title: "619 Distressed Mesh Football Jersey", price: "110.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: t3, rating: 3.7, description: "Distressed mesh jersey with deliberate rip-and-repair detailing for a raw, worn-in finish straight off the rack. The breathable mesh fabric keeps it light for warm days, while the relaxed drop-shoulder cut leaves room to stack a long sleeve or hoodie underneath. Ribbed v-neck collar and side slits at the hem round out the athletic-meets-street silhouette." },
  { id: "sw-08", title: "Dragon Embroidered Leather Biker Jacket", price: "340.00", tag: "LIMITED", sizes: ["M", "L", "XL"], image: c2, rating: 4.9, description: "Full-grain leather biker jacket with a hand-embroidered dragon artwork sprawled across the back panel — the kind of detail you only notice up close. Asymmetric front zip, heavy metal hardware, and a fitted waist give it that classic moto edge. Fully lined interior adds warmth without adding weight. A true statement outerwear piece for anyone building a signature look." },
  { id: "sw-09", title: "Floral Embroidered Cotton Overshirt Jacket", price: "265.00", tag: null, sizes: ["S", "M", "L", "XL"], image: c3, rating: 4.0, description: "Midweight brushed cotton overshirt with floral embroidery running along the yoke, cuffs, and chest pocket. Works layered open over a plain tee for texture, or buttoned all the way as a standalone shirt-jacket on cooler days. Corozo-style buttons and a boxy dropped shoulder complete the vintage-inspired silhouette." },
  { id: "sw-10", title: "Arabic Calligraphy Two-Tone Oversized Hoodie", price: "150.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: c4, rating: 4.4, description: "Two-tone fleece hoodie featuring bold Arabic calligraphy graphics printed across the front and back panels. Built oversized with dropped shoulders and an extra-roomy hood lined for warmth. The heavyweight 320gsm fleece resists pilling and keeps its shape through heavy rotation. A statement hoodie meant to be the focal point of the fit." },
  { id: "sw-11", title: "Revenge of the Sith Zip-Up Hoodie — Star Wars Collab", price: "130.00", tag: "NEW", sizes: ["S", "M", "L", "XL"], image: h1, rating: 4.8, description: "Officially licensed Star Wars zip hoodie featuring embroidered Revenge of the Sith artwork on the chest — not a print, so it won't crack or fade. Fleece-lined hood and ribbed cuffs and hem give it a snug, structured fit built for daily wear. YKK-style zipper pull adds a durable finishing touch to a collab piece made to last." },
  { id: "sw-12", title: "Diablo Retro Graphic Pullover Hoodie — Blizzard Collab", price: "125.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: h2, rating: 4.5, description: "Retro-inspired Diablo graphic printed across heavyweight pullover fleece, pulling directly from the game's classic box art. Roomy kangaroo pocket and an oversized hood make this a staple for stacking under jackets in colder months. Garment-washed for softness from the first wear, with a drop-shoulder cut that keeps the fit relaxed." },
  { id: "sw-13", title: "Xbox OG 'Play More' Pullover Hoodie — Xbox Collab", price: "120.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: h3, rating: 3.8, description: "Throwback Xbox branding printed on soft-brushed fleece for a nostalgic nod to early-2000s gaming culture. Relaxed fit through the body pairs with ribbed cuffs and hem for a clean, tapered finish. Double-layered hood holds its shape whether up or down, making this an easy everyday pullover for gamers and streetwear fans alike." },
  { id: "sw-14", title: "Veirdo Brown Raglan Oversized Tee", price: "65.00", tag: "NEW", sizes: ["S", "M", "L", "XL"], image: top1, rating: 4.3, description: "Raglan-sleeve tee in a warm brown tone with an oversized drop-shoulder cut that layers easily under jackets or hoodies. Lightweight 220gsm cotton keeps it breathable for year-round wear, while the raglan seam construction adds a subtle athletic detail most basic tees skip. A quiet, versatile piece built to anchor any fit." },
  { id: "sw-15", title: "Fellowship of the Ring Graphic Tee", price: "75.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: top2, rating: 4.6, description: "Fellowship-inspired graphic print on a heavyweight 240gsm cotton tee, built oversized with dropped shoulders for that stacked silhouette. The faded, pre-washed finish gives it a broken-in look right away and only gets better with age. A must-have for fans wanting their fandom pieces to actually look like streetwear, not merch." },
  { id: "sw-16", title: "Royal Heritage Printed Oversized Tee", price: "90.00", tag: "LIMITED", sizes: ["M", "L", "XL"], image: top3, rating: 4.9, description: "Ornate heritage-inspired print sprawled across an oversized tee body, drawing from regal motifs and vintage tapestry patterns. Heavyweight cotton construction holds structure through the boxy, drop-shoulder silhouette without sagging over time. Limited production run — once these sell out, they're gone for good." },
  { id: "sw-17", title: "Persian Carpet Pattern Bomber Jacket", price: "280.00", tag: "NEW", sizes: ["M", "L", "XL"], image: top5, rating: 4.2, description: "Intricate Persian carpet-inspired pattern printed edge-to-edge across a structured bomber shell, turning a classic silhouette into a full canvas piece. Ribbed collar, cuffs, and hem lock in the traditional bomber shape, while the satin-touch lining adds a premium feel on the inside. A conversation-starter jacket built for those who want their outerwear to do the talking." },
];

export const Layerdown = [
  { id: "lw-01", title: "Raw Denim Wide-Leg Baggy Pants", price: "175.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: p1, rating: 4.4, description: "Raw, unwashed denim in a wide-leg baggy cut built to age with you. Stiff and dark straight off the shelf, it naturally fades and creases at the knees and seat with wear, developing a pattern unique to how you move. Five-pocket construction and a mid-rise waist keep it functional while the dramatic leg opening delivers the full baggy silhouette." },
  { id: "lw-02", title: "Camouflage Print Wide-Leg Cargo Pants", price: "155.00", tag: "SOLDOUT", sizes: [], image: p2, rating: 3.9, description: "Camo-printed cargo pants with a wide-leg drop and reinforced utility pockets down each thigh. Built from heavyweight cotton twill designed to handle daily movement without wearing thin. Adjustable drawstring waist and tapered ankle cuffs balance out the oversized leg for a controlled, intentional fit." },
  { id: "lw-03", title: "Vintage Wash Wide-Leg Denim Jeans", price: "145.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: p3, rating: 4.5, description: "Vintage-washed denim with natural whiskering and fading already built in, paired with a relaxed wide-leg fit through the thigh and knee. Classic five-pocket styling and a mid-rise waist keep it grounded in traditional denim design while the wide leg keeps the silhouette current. A dependable everyday jean that pairs with almost anything." },
  { id: "lw-04", title: "Cocoa Oversized Hoodie & Cargo Set", price: "195.00", tag: "NEW", sizes: ["S", "M", "L", "XL", "XXL"], image: c1, rating: 4.7, description: "A matching two-piece set in a warm cocoa tone, pairing an oversized fleece hoodie with a tapered cargo pant for a coordinated fit straight out of the box. The hoodie is cut with dropped shoulders and a roomy hood, while the cargo pant balances the volume with a tapered ankle and functional side pockets. Sold as a set so you never have to guess what pairs well." },
  { id: "lw-05", title: "Light Blue Faded Baggy Jeans", price: "165.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: b1, rating: 4.1, description: "Light-wash denim with a naturally faded, sun-bleached finish and a roomy baggy leg from hip to ankle. Built from heavyweight cotton denim that softens with every wash while holding its shape. The lighter tone makes it an easy pairing for darker tees, hoodies, and jackets." },
  { id: "lw-06", title: "Dark Wash Black Baggy Jeans", price: "165.00", tag: "NEW", sizes: ["S", "M", "L", "XL", "XXL"], image: b2, rating: 4.6, description: "Deep black wash on a wide, baggy denim silhouette with minimal fading for a clean, uniform look. The oversized leg opening delivers that stacked, pooling-at-the-ankle streetwear fit, while reinforced stitching at the stress points keeps it holding up through regular wear. A foundational black jean for building fits around." },
  { id: "lw-07", title: "Burgundy Wash Wide-Leg Jeans", price: "175.00", tag: "LIMITED", sizes: ["M", "L", "XL"], image: b3, rating: 4.8, description: "Burgundy-washed denim in a wide-leg cut that stands out in a sea of blue and black without trying too hard. Heavyweight fabric holds its structure through daily wear while the wash deepens with age. Limited colorway — a bold alternative for anyone tired of the usual denim tones." },
  { id: "lw-08", title: "Brown Linen Wide-Leg Trousers", price: "135.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: b4, rating: 4.0, description: "Lightweight linen trousers cut with a wide-leg drape that moves easily and breathes in warm weather. Clean, minimal detailing with a flat front and side pockets keeps them versatile enough to dress up with a button-down or down with a plain tee. An easy pick for anyone wanting texture without extra bulk." },
  { id: "lw-09", title: "Brown Linen Drawstring Baggy Pants", price: "125.00", tag: null, sizes: ["S", "M", "L", "XL", "XXL"], image: b5, rating: 3.8, description: "Breathable linen pants with an adjustable drawstring waist and a loose, baggy fit built for warm-weather comfort. The relaxed drape through the leg keeps airflow moving while the drawstring lets you dial in the fit at the waist. A low-effort, high-comfort pant for travel days or lounging alike." },
];

export const cloths = { Layerup, Layerdown };